Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/precise32"
  config.vm.provision :shell, path: "../Scripts/rabbitmq.sh"
  config.vm.network "private_network", ip: "192.168.50.84"
  config.vm.hostname = "local-rabbitmq08"
end
