Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/precise32"
  config.vm.provision :shell, path: "../Scripts/rabbitmq_cluster5678_disc.sh"
  config.vm.network "private_network", ip: "192.168.50.64"
  config.vm.hostname = "local-rabbitmq06"
end
