Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/precise32"
  config.vm.provision :shell, path: "../Scripts/rabbitmq_cluster5678_1.sh"
  config.vm.network "private_network", ip: "192.168.50.54"
  config.vm.hostname = "local-rabbitmq05"
end
